# Generated by Django 3.2.6 on 2021-08-22 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetofilmes',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 14, 44, 43, 73583), verbose_name='Lista publicada em'),
        ),
    ]
