# Generated by Django 3.2.6 on 2021-08-22 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projetofilmes_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetofilmes',
            name='titulo',
        ),
        migrations.AddField(
            model_name='projetofilmes',
            name='filme',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projetofilmes',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 20, 49, 52, 258188), verbose_name='Lista publicada em'),
        ),
    ]
